/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -i cmdline.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <dirent.h>
#include <stdlib.h>
#include <string.h>
#include "cmdUtils.h"
#include <experimental/filesystem>
#include <cstdint>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: complexnets [OPTIONS]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "ComplexNets description";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "\n Group: network-load\n  Load a network",
  "  -i, --input-file=<filename>   Load a network from an input file",
  "      --weighted                Specify if the input file is considered as a\n                                  weighted graph",
  "      --digraph                 Specify if the input file is considered as a\n                                  digraph",
  "\n Group: model\n  Generate a network using a model",
  "      --erdos                   Erdos-Renyi model",
  "      --barabasi                Barabasi-Albert model",
  "      --hot                     Extended Hot model",
  "      --molloy                  Molloy-Reed model",
  "      --hyperbolic              Papadopoulos Hyperbolic model",
  "  -n, --n=<number>              Number of network nodes.",
  "  -p, --p=<probability>         Connection probability (only for Erdos-Renyi\n                                  model).",
  "  -c, --m0=<number>             Initial number of nodes (only for\n                                  Barabasi-Albert model).  (default=`10')",
  "  -m, --m=<number>              Number of edges to attach from new node to\n                                  existing nodes (Barabasi-Albert model).\n                                  Number of edges in each new vertex (Extended\n                                  Hot Model).",
  "  -x, --xi=<number>             Parameter used to select the neighbors for a\n                                  new vertex (only for Extended Hot Model).",
  "  -q, --q=<number>              Number of edges added in the graph after of\n                                  connect a vertex (only for Extended Hot\n                                  Model).",
  "  -r, --r=<number>              Parameter user to selected the edges in the\n                                  graph after connecting a vertex (only for\n                                  Extended Hot Model).",
  "  -k, --ks=<filename>           Input file that specifies, for each K, how many\n                                  nodes have that K.",
  "  -d, --deg=<number>             Avg degree of nodes parameter (only for\n                                  hyperbolic model).  (default=`0.0014')",
  "  -a, --a=<number>              Radial density of nodes (only for hyperbolic\n                                  model).  (default=`0.75')",
  "\n Group: analysis\n  Network analysis methods",
  "      --betweenness=<vertex id> Calculate betweenness of a given node",
  "      --ddist=<degree>          Calculate the number of nodes with a given\n                                  degree",
  "      --clustering=<vertex id>  Calculate the clustering coefficient of a given\n                                  node",
  "      --knn=<vertex id>         Calculate the nearest neighbors degree of a\n                                  given node",
  "      --shell=<vertex id>       Calculate the shell index of a given node",
  "      --maxCliqueExact=<max time>\n                                Calculate max clique if time (in seconds) is\n                                  enough",
  "      --maxCliqueAprox          Calculate max clique aproximation",
  "      --out                     Use out degrees (directed)  (default=off)",
  "      --in                      Use in degrees (directed) (use --in --out to\n                                  use in and out degrees)  (default=off)",
  "      --betweenness-output      Betweenness vs. Degree",
  "      --ddist-output            Degree distribution",
  "      --log-bin=<number of bins>\n                                Log-bin the output (only for Degree\n                                  distribution)",
  "      --clustering-output       Clustering coefficient vs. Degree",
  "      --knn-output              Nearest Neighbors Degree vs. Degree",
  "      --shell-output            Shell index vs. Degree",
  "      --maxCliqueExact-output=<max time>\n                                ",
  "      --maxCliqueAprox-output   ",
  "  -o, --output-file=<filename>  Save the result in an output file",
  "      --print-deg               Print node degree for power law regression",
  "      --clear-results           Deletes the results calculated stored in the result folder",
  "      --view-results            Shows all the analysis made on each graph",
  "      --plot-results <graph_name>          Uses gnuplot to plot the analysis made for agiven graph",
  "      --view <graph_name> <analysis_name>  Shows the corresponding result for a given graph and analysis previously made.",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_file_given = 0 ;
  args_info->weighted_given = 0 ;
  args_info->digraph_given = 0 ;
  args_info->erdos_given = 0 ;
  args_info->barabasi_given = 0 ;
  args_info->hot_given = 0 ;
  args_info->molloy_given = 0 ;
  args_info->hyperbolic_given = 0 ;
  args_info->n_given = 0 ;
  args_info->p_given = 0 ;
  args_info->m0_given = 0 ;
  args_info->m_given = 0 ;
  args_info->xi_given = 0 ;
  args_info->q_given = 0 ;
  args_info->r_given = 0 ;
  args_info->ks_given = 0 ;
  args_info->deg_given = 0 ;
  args_info->a_given = 0 ;
  args_info->betweenness_given = 0 ;
  args_info->ddist_given = 0 ;
  args_info->clustering_given = 0 ;
  args_info->knn_given = 0 ;
  args_info->shell_given = 0 ;
  args_info->maxCliqueExact_given = 0 ;
  args_info->maxCliqueAprox_given = 0 ;
  args_info->out_given = 0 ;
  args_info->in_given = 0 ;
  args_info->betweenness_output_given = 0 ;
  args_info->ddist_output_given = 0 ;
  args_info->log_bin_given = 0 ;
  args_info->clustering_output_given = 0 ;
  args_info->knn_output_given = 0 ;
  args_info->shell_output_given = 0 ;
  args_info->maxCliqueExact_output_given = 0 ;
  args_info->maxCliqueAprox_output_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->print_deg_given = 0 ;
  args_info->analysis_group_counter = 0 ;
  args_info->directed_group_counter = 0 ;
  args_info->model_group_counter = 0 ;
  args_info->network_load_group_counter = 0 ;
  args_info->output_group_counter = 0 ;

}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->input_file_arg = NULL;
  args_info->input_file_orig = NULL;
  args_info->n_orig = NULL;
  args_info->p_orig = NULL;
  args_info->m0_arg = 10;
  args_info->m0_orig = NULL;
  args_info->m_orig = NULL;
  args_info->xi_orig = NULL;
  args_info->q_orig = NULL;
  args_info->r_orig = NULL;
  args_info->ks_arg = NULL;
  args_info->ks_orig = NULL;
  args_info->deg_arg = 0.0014;
  args_info->deg_orig = NULL;
  args_info->a_arg = 0.75;
  args_info->a_orig = NULL;
  args_info->betweenness_orig = NULL;
  args_info->ddist_orig = NULL;
  args_info->clustering_orig = NULL;
  args_info->knn_orig = NULL;
  args_info->shell_orig = NULL;
  args_info->maxCliqueExact_orig = NULL;
  args_info->out_flag = 0;
  args_info->in_flag = 0;
  args_info->log_bin_orig = NULL;
  args_info->maxCliqueExact_output_orig = NULL;
  args_info->output_file_arg = NULL;
  args_info->output_file_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_file_help = gengetopt_args_info_help[3] ;
  args_info->weighted_help = gengetopt_args_info_help[4] ;
  args_info->digraph_help = gengetopt_args_info_help[5] ;
  args_info->erdos_help = gengetopt_args_info_help[7] ;
  args_info->barabasi_help = gengetopt_args_info_help[8] ;
  args_info->hot_help = gengetopt_args_info_help[9] ;
  args_info->molloy_help = gengetopt_args_info_help[10] ;
  args_info->hyperbolic_help = gengetopt_args_info_help[11] ;
  args_info->n_help = gengetopt_args_info_help[12] ;
  args_info->p_help = gengetopt_args_info_help[13] ;
  args_info->m0_help = gengetopt_args_info_help[14] ;
  args_info->m_help = gengetopt_args_info_help[15] ;
  args_info->xi_help = gengetopt_args_info_help[16] ;
  args_info->q_help = gengetopt_args_info_help[17] ;
  args_info->r_help = gengetopt_args_info_help[18] ;
  args_info->ks_help = gengetopt_args_info_help[19] ;
  args_info->deg_help = gengetopt_args_info_help[20] ;
  args_info->a_help = gengetopt_args_info_help[21] ;
  args_info->betweenness_help = gengetopt_args_info_help[23] ;
  args_info->ddist_help = gengetopt_args_info_help[24] ;
  args_info->clustering_help = gengetopt_args_info_help[25] ;
  args_info->knn_help = gengetopt_args_info_help[26] ;
  args_info->shell_help = gengetopt_args_info_help[27] ;
  args_info->maxCliqueExact_help = gengetopt_args_info_help[28] ;
  args_info->maxCliqueAprox_help = gengetopt_args_info_help[29] ;
  args_info->out_help = gengetopt_args_info_help[30] ;
  args_info->in_help = gengetopt_args_info_help[31] ;
  args_info->betweenness_output_help = gengetopt_args_info_help[32] ;
  args_info->ddist_output_help = gengetopt_args_info_help[33] ;
  args_info->log_bin_help = gengetopt_args_info_help[34] ;
  args_info->clustering_output_help = gengetopt_args_info_help[35] ;
  args_info->knn_output_help = gengetopt_args_info_help[36] ;
  args_info->shell_output_help = gengetopt_args_info_help[37] ;
  args_info->maxCliqueExact_output_help = gengetopt_args_info_help[38] ;
  args_info->maxCliqueAprox_output_help = gengetopt_args_info_help[39] ;
  args_info->output_file_help = gengetopt_args_info_help[40] ;
  args_info->print_deg_help = gengetopt_args_info_help[41] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->input_file_arg));
  free_string_field (&(args_info->input_file_orig));
  free_string_field (&(args_info->n_orig));
  free_string_field (&(args_info->p_orig));
  free_string_field (&(args_info->m0_orig));
  free_string_field (&(args_info->m_orig));
  free_string_field (&(args_info->xi_orig));
  free_string_field (&(args_info->q_orig));
  free_string_field (&(args_info->r_orig));
  free_string_field (&(args_info->ks_arg));
  free_string_field (&(args_info->ks_orig));
  free_string_field (&(args_info->deg_orig));
  free_string_field (&(args_info->a_orig));
  free_string_field (&(args_info->betweenness_orig));
  free_string_field (&(args_info->ddist_orig));
  free_string_field (&(args_info->clustering_orig));
  free_string_field (&(args_info->knn_orig));
  free_string_field (&(args_info->shell_orig));
  free_string_field (&(args_info->maxCliqueExact_orig));
  free_string_field (&(args_info->log_bin_orig));
  free_string_field (&(args_info->maxCliqueExact_output_orig));
  free_string_field (&(args_info->output_file_arg));
  free_string_field (&(args_info->output_file_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->input_file_given)
    write_into_file(outfile, "input-file", args_info->input_file_orig, 0);
  if (args_info->weighted_given)
    write_into_file(outfile, "weighted", 0, 0 );
  if (args_info->digraph_given)
    write_into_file(outfile, "digraph", 0, 0 );
  if (args_info->erdos_given)
    write_into_file(outfile, "erdos", 0, 0 );
  if (args_info->barabasi_given)
    write_into_file(outfile, "barabasi", 0, 0 );
  if (args_info->hot_given)
    write_into_file(outfile, "hot", 0, 0 );
  if (args_info->molloy_given)
    write_into_file(outfile, "molloy", 0, 0 );
  if (args_info->hyperbolic_given)
    write_into_file(outfile, "hyperbolic", 0, 0 );
  if (args_info->n_given)
    write_into_file(outfile, "n", args_info->n_orig, 0);
  if (args_info->p_given)
    write_into_file(outfile, "p", args_info->p_orig, 0);
  if (args_info->m0_given)
    write_into_file(outfile, "m0", args_info->m0_orig, 0);
  if (args_info->m_given)
    write_into_file(outfile, "m", args_info->m_orig, 0);
  if (args_info->xi_given)
    write_into_file(outfile, "xi", args_info->xi_orig, 0);
  if (args_info->q_given)
    write_into_file(outfile, "q", args_info->q_orig, 0);
  if (args_info->r_given)
    write_into_file(outfile, "r", args_info->r_orig, 0);
  if (args_info->ks_given)
    write_into_file(outfile, "ks", args_info->ks_orig, 0);
  if (args_info->deg_given)
    write_into_file(outfile, "deg", args_info->deg_orig, 0);
  if (args_info->a_given)
    write_into_file(outfile, "a", args_info->a_orig, 0);
  if (args_info->betweenness_given)
    write_into_file(outfile, "betweenness", args_info->betweenness_orig, 0);
  if (args_info->ddist_given)
    write_into_file(outfile, "ddist", args_info->ddist_orig, 0);
  if (args_info->clustering_given)
    write_into_file(outfile, "clustering", args_info->clustering_orig, 0);
  if (args_info->knn_given)
    write_into_file(outfile, "knn", args_info->knn_orig, 0);
  if (args_info->shell_given)
    write_into_file(outfile, "shell", args_info->shell_orig, 0);
  if (args_info->maxCliqueExact_given)
    write_into_file(outfile, "maxCliqueExact", args_info->maxCliqueExact_orig, 0);
  if (args_info->maxCliqueAprox_given)
    write_into_file(outfile, "maxCliqueAprox", 0, 0 );
  if (args_info->out_given)
    write_into_file(outfile, "out", 0, 0 );
  if (args_info->in_given)
    write_into_file(outfile, "in", 0, 0 );
  if (args_info->betweenness_output_given)
    write_into_file(outfile, "betweenness-output", 0, 0 );
  if (args_info->ddist_output_given)
    write_into_file(outfile, "ddist-output", 0, 0 );
  if (args_info->log_bin_given)
    write_into_file(outfile, "log-bin", args_info->log_bin_orig, 0);
  if (args_info->clustering_output_given)
    write_into_file(outfile, "clustering-output", 0, 0 );
  if (args_info->knn_output_given)
    write_into_file(outfile, "knn-output", 0, 0 );
  if (args_info->shell_output_given)
    write_into_file(outfile, "shell-output", 0, 0 );
  if (args_info->maxCliqueExact_output_given)
    write_into_file(outfile, "maxCliqueExact-output", args_info->maxCliqueExact_output_orig, 0);
  if (args_info->maxCliqueAprox_output_given)
    write_into_file(outfile, "maxCliqueAprox-output", 0, 0 );
  if (args_info->output_file_given)
    write_into_file(outfile, "output-file", args_info->output_file_orig, 0);
  if (args_info->print_deg_given)
    write_into_file(outfile, "print-deg", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");
  fprintf(stderr, "%s\n", filename);

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_analysis(struct gengetopt_args_info *args_info)
{
  if (! args_info->analysis_group_counter)
    return;
  
  args_info->betweenness_given = 0 ;
  free_string_field (&(args_info->betweenness_orig));
  args_info->ddist_given = 0 ;
  free_string_field (&(args_info->ddist_orig));
  args_info->clustering_given = 0 ;
  free_string_field (&(args_info->clustering_orig));
  args_info->knn_given = 0 ;
  free_string_field (&(args_info->knn_orig));
  args_info->shell_given = 0 ;
  free_string_field (&(args_info->shell_orig));
  args_info->maxCliqueExact_given = 0 ;
  free_string_field (&(args_info->maxCliqueExact_orig));
  args_info->maxCliqueAprox_given = 0 ;

  args_info->analysis_group_counter = 0;
}

static void
reset_group_model(struct gengetopt_args_info *args_info)
{
  if (! args_info->model_group_counter)
    return;
  
  args_info->erdos_given = 0 ;
  args_info->barabasi_given = 0 ;
  args_info->hot_given = 0 ;
  args_info->molloy_given = 0 ;
  args_info->hyperbolic_given = 0 ;

  args_info->model_group_counter = 0;
}

static void
reset_group_network_load(struct gengetopt_args_info *args_info)
{
  if (! args_info->network_load_group_counter)
    return;
  
  args_info->input_file_given = 0 ;
  free_string_field (&(args_info->input_file_arg));
  free_string_field (&(args_info->input_file_orig));

  args_info->network_load_group_counter = 0;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  
  /* checks for dependences among options */
  if (args_info->weighted_given && ! args_info->input_file_given)
    {
      fprintf (stderr, "%s: '--weighted' option depends on option 'input-file'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->digraph_given && ! args_info->input_file_given)
    {
      fprintf (stderr, "%s: '--digraph' option depends on option 'input-file'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->m0_given && ! args_info->barabasi_given)
    {
      fprintf (stderr, "%s: '--m0' ('-c') option depends on option 'barabasi'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->xi_given && ! args_info->hot_given)
    {
      fprintf (stderr, "%s: '--xi' ('-x') option depends on option 'hot'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->q_given && ! args_info->hot_given)
    {
      fprintf (stderr, "%s: '--q' ('-q') option depends on option 'hot'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->r_given && ! args_info->hot_given)
    {
      fprintf (stderr, "%s: '--r' ('-r') option depends on option 'hot'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->ks_given && ! args_info->molloy_given)
    {
      fprintf (stderr, "%s: '--ks' ('-k') option depends on option 'molloy'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->deg_given && ! args_info->hyperbolic_given)
    {
      fprintf (stderr, "%s: '--deg' ('-d') option depends on option 'hyperbolic'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->a_given && ! args_info->hyperbolic_given)
    {
      fprintf (stderr, "%s: '--a' ('-a') option depends on option 'hyperbolic'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->log_bin_given && ! args_info->ddist_output_given)
    {
      fprintf (stderr, "%s: '--log-bin' option depends on option 'ddist-output'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input-file",	1, NULL, 'i' },
        { "weighted",	0, NULL, 0 },
        { "digraph",	0, NULL, 0 },
        { "erdos",	0, NULL, 0 },
        { "barabasi",	0, NULL, 0 },
        { "hot",	0, NULL, 0 },
        { "molloy",	0, NULL, 0 },
        { "hyperbolic",	0, NULL, 0 },
        { "n",	1, NULL, 'n' },
        { "p",	1, NULL, 'p' },
        { "m0",	1, NULL, 'c' },
        { "m",	1, NULL, 'm' },
        { "xi",	1, NULL, 'x' },
        { "q",	1, NULL, 'q' },
        { "r",	1, NULL, 'r' },
        { "ks",	1, NULL, 'k' },
        { "deg",	1, NULL, 'd' },
        { "a",	1, NULL, 'a' },
        { "betweenness",	1, NULL, 0 },
        { "ddist",	1, NULL, 0 },
        { "clustering",	1, NULL, 0 },
        { "knn",	1, NULL, 0 },
        { "shell",	1, NULL, 0 },
        { "maxCliqueExact",	1, NULL, 0 },
        { "maxCliqueAprox",	0, NULL, 0 },
        { "out",	0, NULL, 0 },
        { "in",	0, NULL, 0 },
        { "betweenness-output",	0, NULL, 0 },
        { "ddist-output",	0, NULL, 0 },
        { "log-bin",	1, NULL, 0 },
        { "clustering-output",	0, NULL, 0 },
        { "knn-output",	0, NULL, 0 },
        { "shell-output",	0, NULL, 0 },
        { "maxCliqueExact-output",	1, NULL, 0 },
        { "maxCliqueAprox-output",	0, NULL, 0 },
        { "output-file",	1, NULL, 'o' },
        { "print-deg",	0, NULL, 0 },
        { "clear-results", 0, NULL, 0},
        { "view-results", 0, NULL, 0},
        { "view", 2, NULL, 0},
        { "plot-results", 1, NULL, 0},
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVi:n:p:c:m:x:q:r:k:d:a:o:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* Load a network from an input file.  */
        
          if (args_info->network_load_group_counter && override)
            reset_group_network_load (args_info);
          args_info->network_load_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->input_file_arg), 
               &(args_info->input_file_orig), &(args_info->input_file_given),
              &(local_args_info.input_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input-file", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Number of network nodes..  */
        
        
          if (update_arg( (void *)&(args_info->n_arg), 
               &(args_info->n_orig), &(args_info->n_given),
              &(local_args_info.n_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "n", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Connection probability (only for Erdos-Renyi model)..  */
        
        
          if (update_arg( (void *)&(args_info->p_arg), 
               &(args_info->p_orig), &(args_info->p_given),
              &(local_args_info.p_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "p", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Initial number of nodes (only for Barabasi-Albert model)..  */
        
        
          if (update_arg( (void *)&(args_info->m0_arg), 
               &(args_info->m0_orig), &(args_info->m0_given),
              &(local_args_info.m0_given), optarg, 0, "10", ARG_INT,
              check_ambiguity, override, 0, 0,
              "m0", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Number of edges to attach from new node to existing nodes (Barabasi-Albert model). Number of edges in each new vertex (Extended Hot Model)..  */
        
        
          if (update_arg( (void *)&(args_info->m_arg), 
               &(args_info->m_orig), &(args_info->m_given),
              &(local_args_info.m_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "m", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* Parameter used to select the neighbors for a new vertex (only for Extended Hot Model)..  */
        
        
          if (update_arg( (void *)&(args_info->xi_arg), 
               &(args_info->xi_orig), &(args_info->xi_given),
              &(local_args_info.xi_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "xi", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Number of edges added in the graph after of connect a vertex (only for Extended Hot Model)..  */
        
        
          if (update_arg( (void *)&(args_info->q_arg), 
               &(args_info->q_orig), &(args_info->q_given),
              &(local_args_info.q_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "q", 'q',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Parameter user to selected the edges in the graph after connecting a vertex (only for Extended Hot Model)..  */
        
        
          if (update_arg( (void *)&(args_info->r_arg), 
               &(args_info->r_orig), &(args_info->r_given),
              &(local_args_info.r_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "r", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* Input file that specifies, for each K, how many nodes have that K..  */
        
        
          if (update_arg( (void *)&(args_info->ks_arg), 
               &(args_info->ks_orig), &(args_info->ks_given),
              &(local_args_info.ks_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "ks", 'k',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/*  Avg degree of nodes parameter (only for hyperbolic model)..  */
        
        
          if (update_arg( (void *)&(args_info->deg_arg), 
               &(args_info->deg_orig), &(args_info->deg_given),
              &(local_args_info.deg_given), optarg, 0, "0.0014", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "deg", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Radial density of nodes (only for hyperbolic model)..  */
        
        
          if (update_arg( (void *)&(args_info->a_arg), 
               &(args_info->a_orig), &(args_info->a_given),
              &(local_args_info.a_given), optarg, 0, "0.75", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "a", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Save the result in an output file.  */
        
        
          if (update_arg( (void *)&(args_info->output_file_arg), 
               &(args_info->output_file_orig), &(args_info->output_file_given),
              &(local_args_info.output_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output-file", 'o',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Specify if the input file is considered as a weighted graph.  */
          if (strcmp (long_options[option_index].name, "weighted") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->weighted_given),
                &(local_args_info.weighted_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "weighted", '-',
                additional_error))
              goto failure;
          
          }
          /* Specify if the input file is considered as a digraph.  */
          else if (strcmp (long_options[option_index].name, "digraph") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->digraph_given),
                &(local_args_info.digraph_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "digraph", '-',
                additional_error))
              goto failure;
          
          }
          /* Erdos-Renyi model.  */
          else if (strcmp (long_options[option_index].name, "erdos") == 0)
          {
          
            if (args_info->model_group_counter && override)
              reset_group_model (args_info);
            args_info->model_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->erdos_given),
                &(local_args_info.erdos_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "erdos", '-',
                additional_error))
              goto failure;
          
          }
          /* Barabasi-Albert model.  */
          else if (strcmp (long_options[option_index].name, "barabasi") == 0)
          {
          
            if (args_info->model_group_counter && override)
              reset_group_model (args_info);
            args_info->model_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->barabasi_given),
                &(local_args_info.barabasi_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "barabasi", '-',
                additional_error))
              goto failure;
          
          }
          /* Extended Hot model.  */
          else if (strcmp (long_options[option_index].name, "hot") == 0)
          {
          
            if (args_info->model_group_counter && override)
              reset_group_model (args_info);
            args_info->model_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->hot_given),
                &(local_args_info.hot_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "hot", '-',
                additional_error))
              goto failure;
          
          }
          /* Molloy-Reed model.  */
          else if (strcmp (long_options[option_index].name, "molloy") == 0)
          {
          
            if (args_info->model_group_counter && override)
              reset_group_model (args_info);
            args_info->model_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->molloy_given),
                &(local_args_info.molloy_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "molloy", '-',
                additional_error))
              goto failure;
          
          }
          /* Papadopoulos Hyperbolic model.  */
          else if (strcmp (long_options[option_index].name, "hyperbolic") == 0)
          {
          
            if (args_info->model_group_counter && override)
              reset_group_model (args_info);
            args_info->model_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->hyperbolic_given),
                &(local_args_info.hyperbolic_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "hyperbolic", '-',
                additional_error))
              goto failure;
          
          }
          /* Calculate betweenness of a given node.  */
          else if (strcmp (long_options[option_index].name, "betweenness") == 0)
          {
          
            if (args_info->analysis_group_counter && override)
              reset_group_analysis (args_info);
            args_info->analysis_group_counter += 1;
          
            if (update_arg( (void *)&(args_info->betweenness_arg), 
                 &(args_info->betweenness_orig), &(args_info->betweenness_given),
                &(local_args_info.betweenness_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "betweenness", '-',
                additional_error))
              goto failure;
          
          }
          /* Calculate the number of nodes with a given degree.  */
          else if (strcmp (long_options[option_index].name, "ddist") == 0)
          {
          
            if (args_info->analysis_group_counter && override)
              reset_group_analysis (args_info);
            args_info->analysis_group_counter += 1;
          
            if (update_arg( (void *)&(args_info->ddist_arg), 
                 &(args_info->ddist_orig), &(args_info->ddist_given),
                &(local_args_info.ddist_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "ddist", '-',
                additional_error))
              goto failure;
          
          }
          /* Calculate the clustering coefficient of a given node.  */
          else if (strcmp (long_options[option_index].name, "clustering") == 0)
          {
          
            if (args_info->analysis_group_counter && override)
              reset_group_analysis (args_info);
            args_info->analysis_group_counter += 1;
          
            if (update_arg( (void *)&(args_info->clustering_arg), 
                 &(args_info->clustering_orig), &(args_info->clustering_given),
                &(local_args_info.clustering_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "clustering", '-',
                additional_error))
              goto failure;
          
          }
          /* Calculate the nearest neighbors degree of a given node.  */
          else if (strcmp (long_options[option_index].name, "knn") == 0)
          {
          
            if (args_info->analysis_group_counter && override)
              reset_group_analysis (args_info);
            args_info->analysis_group_counter += 1;
          
            if (update_arg( (void *)&(args_info->knn_arg), 
                 &(args_info->knn_orig), &(args_info->knn_given),
                &(local_args_info.knn_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "knn", '-',
                additional_error))
              goto failure;
          
          }
          /* Calculate the shell index of a given node.  */
          else if (strcmp (long_options[option_index].name, "shell") == 0)
          {
          
            if (args_info->analysis_group_counter && override)
              reset_group_analysis (args_info);
            args_info->analysis_group_counter += 1;
          
            if (update_arg( (void *)&(args_info->shell_arg), 
                 &(args_info->shell_orig), &(args_info->shell_given),
                &(local_args_info.shell_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "shell", '-',
                additional_error))
              goto failure;
          
          }
          /* Calculate max clique if time (in seconds) is enough.  */
          else if (strcmp (long_options[option_index].name, "maxCliqueExact") == 0)
          {
          
            if (args_info->analysis_group_counter && override)
              reset_group_analysis (args_info);
            args_info->analysis_group_counter += 1;
          
            if (update_arg( (void *)&(args_info->maxCliqueExact_arg), 
                 &(args_info->maxCliqueExact_orig), &(args_info->maxCliqueExact_given),
                &(local_args_info.maxCliqueExact_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "maxCliqueExact", '-',
                additional_error))
              goto failure;
          
          }
          /* Calculate max clique aproximation.  */
          else if (strcmp (long_options[option_index].name, "maxCliqueAprox") == 0)
          {
          
            if (args_info->analysis_group_counter && override)
              reset_group_analysis (args_info);
            args_info->analysis_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->maxCliqueAprox_given),
                &(local_args_info.maxCliqueAprox_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "maxCliqueAprox", '-',
                additional_error))
              goto failure;
          
          }
          /* Use out degrees (directed).  */
          else if (strcmp (long_options[option_index].name, "out") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->out_flag), 0, &(args_info->out_given),
                &(local_args_info.out_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "out", '-',
                additional_error))
              goto failure;
          
          }
          /* Use in degrees (directed) (use --in --out to use in and out degrees).  */
          else if (strcmp (long_options[option_index].name, "in") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->in_flag), 0, &(args_info->in_given),
                &(local_args_info.in_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "in", '-',
                additional_error))
              goto failure;
          
          }
          /* Betweenness vs. Degree.  */
          else if (strcmp (long_options[option_index].name, "betweenness-output") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->betweenness_output_given),
                &(local_args_info.betweenness_output_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "betweenness-output", '-',
                additional_error))
              goto failure;
          
          }
          /* Degree distribution.  */
          else if (strcmp (long_options[option_index].name, "ddist-output") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->ddist_output_given),
                &(local_args_info.ddist_output_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ddist-output", '-',
                additional_error))
              goto failure;
          
          }
          /* Log-bin the output (only for Degree distribution).  */
          else if (strcmp (long_options[option_index].name, "log-bin") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->log_bin_arg), 
                 &(args_info->log_bin_orig), &(args_info->log_bin_given),
                &(local_args_info.log_bin_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "log-bin", '-',
                additional_error))
              goto failure;
          
          }
          /* Clustering coefficient vs. Degree.  */
          else if (strcmp (long_options[option_index].name, "clustering-output") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->clustering_output_given),
                &(local_args_info.clustering_output_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "clustering-output", '-',
                additional_error))
              goto failure;
          
          }
          /* Nearest Neighbors Degree vs. Degree.  */
          else if (strcmp (long_options[option_index].name, "knn-output") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->knn_output_given),
                &(local_args_info.knn_output_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "knn-output", '-',
                additional_error))
              goto failure;
          
          }
          /* Shell index vs. Degree.  */
          else if (strcmp (long_options[option_index].name, "shell-output") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->shell_output_given),
                &(local_args_info.shell_output_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "shell-output", '-',
                additional_error))
              goto failure;
          
          }
          /* .  */
          else if (strcmp (long_options[option_index].name, "maxCliqueExact-output") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->maxCliqueExact_output_arg), 
                 &(args_info->maxCliqueExact_output_orig), &(args_info->maxCliqueExact_output_given),
                &(local_args_info.maxCliqueExact_output_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "maxCliqueExact-output", '-',
                additional_error))
              goto failure;
          
          }
          /* .  */
          else if (strcmp (long_options[option_index].name, "maxCliqueAprox-output") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->maxCliqueAprox_output_given),
                &(local_args_info.maxCliqueAprox_output_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "maxCliqueAprox-output", '-',
                additional_error))
              goto failure;
          
          }
          /* Print node degree for power law regression.  */
          else if (strcmp (long_options[option_index].name, "print-deg") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->print_deg_given),
                &(local_args_info.print_deg_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "print-deg", '-',
                additional_error))
              goto failure;
          
          }
          else if (strcmp (long_options[option_index].name, "clear-results") == 0)
          {
            #if defined(WIN32) || defined(_WIN32) || defined(__WIN32) && !defined(__CYGWIN__)
            std::string rm_cmd = "rmdir /S /Q " + std::string(RESULTS_DIR);
            #else
            std::string rm_cmd = "rm -rf " + std::string(RESULTS_DIR) + " 2> /dev/null";
            #endif
            
            const int dir_err = system(rm_cmd.c_str());
            //std::experimental::filesystem::path::remove_all(RESULTS_DIR);
            if (-1 == dir_err)
            {
                printf("Error clearing results directory! \n");
            }
            else if (256 == dir_err)
            {
                printf("Results directory is empty or doesn't exist. \n");
            }
            else
            {
                printf("Results directory cleared succesfully! \n");
            }
            exit(0);
          }
          else if (strcmp (long_options[option_index].name, "view-results") == 0) 
          {
              listdir(RESULTS_DIR, 0);
              exit(0);
          }
          else if (strcmp (long_options[option_index].name, "view") == 0) 
          {
              if (argc < 4) {
                printf("Insufficient arguments ex: complexnets --view <graph_name> <analysis_name>\n");
                exit(1);
              }
              printFile(argv[2], argv[3]);
              exit(0);
          }
          else if (strcmp (long_options[option_index].name, "plot-results") == 0)
          {
              
              if (argc < 3) {
                printf("Insufficient arguments ex: complexnets --plot-results <graph_name>\n");
                exit(1);
              }
              plotResults(argv[2]);
              exit(0);
          }

          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->analysis_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group analysis were given. At most one is required%s.\n", argv[0], args_info->analysis_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (args_info->directed_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group directed were given. At most one is required%s.\n", argv[0], args_info->directed_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (args_info->model_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group model were given. At most one is required%s.\n", argv[0], args_info->model_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (args_info->network_load_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group network-load were given. At most one is required%s.\n", argv[0], args_info->network_load_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (args_info->output_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group output were given. At most one is required%s.\n", argv[0], args_info->output_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  


  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}